language: node_js

node_js: "10"

os:
  - linux
  - osx

branches:
  only:
    - master

git:
  depth: 1

cache:
  directories:
    - node_modules
    - "$HOME/.npm"
    - "$HOME/.cache/yarn/v1"
    - "$HOME/.electron"

addons:
  apt:
    packages:
      - fakeroot
      - dpkg
  homebrew:
    packages:
      - fakeroot
      - dpkg

before_install:
  - echo "Hello before_install."

install:
  - npm install -g npm@6.4.1
  - npm install -g electron-forge@5.2.2
  - yarn

before_script:
  - node --version
  - npm --version
  - yarn cache dir

script:
  - npm run fetch-assets
  - npm run make

after_success:
  - echo "Hello after_success."

after_script:
  - echo "Hello after_script."

