version: "0.1.0.{build}"

skip_non_tags: true

image: Visual Studio 2017

shallow_clone: true

platform:
#  - x86
  - x64

environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn
  - npm install -g electron-forge@5.2.2

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

before_build:
  - node --version
  - npm --version

build_script:
  - echo "Skipping build step."

test_script:
  - echo "Skipping test step."

after_test:
  - npm run fetch-assets
  - npm run make

artifacts:
  - path: 'out\make\**\*.exe'
    name: exe

