version: "{build}"                  # Version used in Appveyor to know this is a unique run, branch/build are only two vars
build: off                          # Disables typical windows building for Visual Studio
platform:                           # Platforms to test/build on
#  - x86                            # Build for 32bit
  - x64                             # Also build and test 64bit
environment:
  nodejs_version: "10"              # Test against the latest version of this Node.js version
install:                            # Install scripts. (runs after repo cloning)
  - ps: Install-Product node $env:nodejs_version # Get the latest stable version of Node.js or io.js
  - npm install                     # install modules
  - npm install -g electron-forge@5.2.2 # install electron-forge cli
cache:
  - node_modules                    # Cache npm install to save a minute on builds
skip_non_tags: true                 # Only build tags (we use travis-ci for tests)
test_script:
  - node --version                  # Helpful debugging info
  - npm --version
  - npm test                        # run tests
after_test:                         # run build after tests
  - npm run make                    # Script to package/compile
artifacts:                          # Add artifacts to upload
  - path: 'out\make\**\*.exe'       # upload all exe files in ./out/make
    name: exe                       # name to be used in deploy

